### ISSUE TITLE
No instance is extracted for this release

### ISSUE THREAD

**Issue by yiikou** [smartshark/mynbou#9]
Hi, With trying multiple releases, I got the same failure information: `Exception: No instances extracted for this release`. What does the "instance" here mean?
![image](https://user-images.githubusercontent.com/6872777/98894787-984db300-2473-11eb-93ec-47cb265c5add.png)

Here is some preconditions: 
1) I chose ant-ivy as an example.
2) All 9 plugins are executed. 
3) Especially, I applied coastSHARK, mecoSHARK, and refSHARK on multiple releases. and following is an example of the commit "e6c3eb6ddc9725f26631d7e3258a2b7d57e23bc6":
![image](https://user-images.githubusercontent.com/6872777/98895044-22961700-2474-11eb-9937-f6d45fa9cd57.png)
![image](https://user-images.githubusercontent.com/6872777/98895080-32adf680-2474-11eb-864a-f8bf68ea2215.png)
![image](https://user-images.githubusercontent.com/6872777/98895087-38a3d780-2474-11eb-8739-3c6e229b37c1.png)

If the instance means the calculated metrics, The figure 3 shows those metrics do exist. How can I fix this problem and what is the proper way to use Mynbou?

Thank you!

PS: the example in the readme seem outdated. Here is my example: `python smartshark_plugin.py -U root -P CHANGEME -DB smartshark -H localhost -p 27018 -a smartshark -pn ivy -rn test_release -tr 0b9db35ee7a94a719e538b04122b86cb997f3a17 -tp SZZ --save-to-mongo`

**Comment by yiikou** [comment]
By debugging, seems the `changemetrics` in core.py #42 is empty... have no clue why it happens..

Here is partial information of Volg object
![image](https://user-images.githubusercontent.com/6872777/98898413-9556c080-247b-11eb-8ae7-6664960b078d.png)

**Comment by atrautsch** [comment]
I am currently running Mynbou on our data for the ant-ivy release 2.4.0, it seems to run fine. Although our data contains the metrics for each revision. The change metrics could be empty if you only have the metrics for the release.

**Comment by yiikou** [comment]
@atrautsch does it mean that it is suggested to run coastSHARK, mecoSHARK, and refSHARK on all revisions (more than 1k+)..... If so, it sounds super time-consuming. Especially, the coastSHARK conflicts with inducingSHARK (in my case), to do that I have to redeploy a new vagrant and recrawl all data again.

I wonder that is there a way to upload Mynbou output (from https://user.informatik.uni-goettingen.de/~sherbol/replicationkits/replication-kit-emse-2020-defect-prediction-data/) to visualSHARK?

**Comment by atrautsch** [comment]
Well, we did it with everything for every commit. Release level defect prediction is simple in that for most approaches you only need the metrics for a release. However, we implemented D'Ambros metrics which add changes in metrics from previous commits so if you want those metrics you need the metrics for previous commits.
It could in theory work without it but I am not sure if in some other parts of mynbou rely on CodeEntityState for file names.
My local installation is not yet up so I can not test it.

If you have a json file you can probably copy paste the code at the bottom of smartshark_plugin.py which writes the MynbouData to write a json file directly. The connection to the MongoDB needs to be setup first.

**Comment by yiikou** [comment]
Thanks for the suggestion, i finnaly import data from the repliation package into visualSHARK, and with some modification, the prediction & evaluation feature work! I have a further question: is the trained model just work at that time? Which means there is no place to store the trained model for now.

And in the product stat tab, what does this big black box mean?
![image](https://user-images.githubusercontent.com/6872777/98964219-8d783a00-24d6-11eb-8535-53e853683618.png)

**Comment by atrautsch** [comment]
This is an explorative feature, the model is trained on-the-fly when you hit the button in the prediction view. It is not stored although that would not be a problem. The code is in visualSHARK/util/prediction.py.

The black box is an error of the FilePathInformation component. It was previously used to explore the project structure by displaying packages and files with different colors depending on the number of bugs. I am attaching an image of a small Java project.
![product_info_paths](https://user-images.githubusercontent.com/5121615/98970250-034cc780-2510-11eb-9b75-0d24193c659b.png)

**Comment by yiikou** [comment]
Thanks for the clarification!

**Comment by atrautsch** [comment]
@yiikou I found the reason for the missing instances. Mynbou requires that the memeSHARK has been run before. The memeSHARK compacts the data and writes a list of CodeEntityStates for each commit which is what the Mynbou tries to find. In case the memeSHARK did not run it is empty and therefore no instances are found.
